import React, { useState } from 'react';
import Navbar from './components/Navbar';
import UrlForm from './components/UrlForm';
import ScanProgress from './components/ScanProgress';
import ReportView from './components/ReportView';
import ApiKeyModal from './components/ApiKeyModal';
import HistoryDrawer from './components/HistoryDrawer';
import { AlertTriangle, ShieldCheck, Eye, Zap, BarChart3, Code2 } from 'lucide-react';

const FEATURE_CARDS = [
  {
    icon: ShieldCheck,
    title: 'Full axe-core Audit',
    desc: 'WCAG 2.1 Level A & AA checks on live JavaScript-rendered pages via headless Chromium.',
    color: '#818cf8',
    bg: 'rgba(99,102,241,0.08)',
    border: 'rgba(99,102,241,0.15)',
  },
  {
    icon: Eye,
    title: 'Visual Bounding Boxes',
    desc: 'Full-page screenshots with severity-coded overlays pinpointing exact DOM violations.',
    color: '#a78bfa',
    bg: 'rgba(167,139,250,0.08)',
    border: 'rgba(167,139,250,0.15)',
  },
  {
    icon: Zap,
    title: 'AI Code Remediator',
    desc: 'Each violation gets a plain-English explanation and production-ready corrected HTML.',
    color: '#f472b6',
    bg: 'rgba(244,114,182,0.08)',
    border: 'rgba(244,114,182,0.15)',
  },
  {
    icon: BarChart3,
    title: 'Accessibility Score',
    desc: 'Weighted A–F grade by violation severity — track progress over time with scan history.',
    color: '#34d399',
    bg: 'rgba(52,211,153,0.08)',
    border: 'rgba(52,211,153,0.15)',
  },
  {
    icon: Code2,
    title: 'AI Diff Viewer',
    desc: 'Side-by-side before/after code diffs generated by Claude, Gemini, or GPT-4o.',
    color: '#60a5fa',
    bg: 'rgba(96,165,250,0.08)',
    border: 'rgba(96,165,250,0.15)',
  },
  {
    icon: ShieldCheck,
    title: 'Export & Share',
    desc: 'Download full JSON reports or annotated screenshots. Copy summaries to clipboard.',
    color: '#fb923c',
    bg: 'rgba(251,146,60,0.08)',
    border: 'rgba(251,146,60,0.15)',
  },
];

export default function App() {
  const [currentReport, setCurrentReport] = useState(null);
  const [isScanning, setIsScanning] = useState(false);
  const [targetUrl, setTargetUrl] = useState('');
  const [scanError, setScanError] = useState('');
  const [apiKey, setApiKey] = useState('');
  const [isApiKeyOpen, setIsApiKeyOpen] = useState(false);
  const [isHistoryOpen, setIsHistoryOpen] = useState(false);

  const handleStartScan = async (url) => {
    setIsScanning(true);
    setTargetUrl(url);
    setScanError('');
    setCurrentReport(null);
    try {
      const res = await fetch('/api/scan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url, api_key: apiKey || undefined }),
      });
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.detail || `Server error ${res.status}`);
      }
      setCurrentReport(await res.json());
    } catch (err) {
      if (err.name === 'TypeError' && err.message?.includes('fetch')) {
        setScanError('Cannot connect to backend. Make sure the Python server is running on port 8000.');
      } else {
        setScanError(err.message || 'Unexpected error during scan.');
      }
    } finally {
      setIsScanning(false);
    }
  };

  const handleSelectHistory = async (scanId) => {
    try {
      const res = await fetch(`/api/report/${scanId}`);
      if (res.ok) { setCurrentReport(await res.json()); setScanError(''); }
      else setScanError('Failed to load report.');
    } catch { setScanError('Cannot connect to backend.'); }
  };

  const showHero = !isScanning && !currentReport && !scanError;

  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', background: '#050810' }}>
      <Navbar onOpenApiKey={() => setIsApiKeyOpen(true)} onToggleHistory={() => setIsHistoryOpen(true)} currentReport={currentReport} />

      <main className="flex-1">
        {/* ── Hero + URL input ── */}
        <section className="relative pt-14 pb-8 overflow-hidden">
          {/* Ambient glows */}
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[700px] h-[400px] pointer-events-none"
            style={{ background: 'radial-gradient(ellipse at 50% 0%, rgba(99,102,241,0.15) 0%, transparent 70%)' }} />
          <div className="absolute top-20 left-[15%] w-64 h-64 rounded-full pointer-events-none"
            style={{ background: 'rgba(139,92,246,0.06)', filter: 'blur(60px)' }} />
          <div className="absolute top-20 right-[15%] w-64 h-64 rounded-full pointer-events-none"
            style={{ background: 'rgba(236,72,153,0.05)', filter: 'blur(60px)' }} />

          <div className="relative max-w-4xl mx-auto text-center px-4 mb-10">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full mb-5 text-[11px] font-bold uppercase tracking-widest"
              style={{ background: 'rgba(99,102,241,0.1)', border: '1px solid rgba(99,102,241,0.2)', color: '#a5b4fc' }}>
              <Zap className="h-3 w-3" />
              Automated WCAG 2.1 Remediation Platform
            </div>

            <h1 className="text-4xl sm:text-5xl md:text-6xl font-black text-white tracking-tight leading-[1.1] mb-5">
              Scan, Visualize &{' '}
              <br className="hidden sm:block" />
              <span className="gradient-text">Auto‑Fix Accessibility</span>
            </h1>

            <p className="text-slate-400 text-base sm:text-lg max-w-2xl mx-auto leading-relaxed">
              Detect WCAG 2.1 violations on live JS-rendered pages with Playwright & axe-core.
              Pinpoint elements visually and get AI-generated production code fixes instantly.
            </p>
          </div>

          <UrlForm onStartScan={handleStartScan} isScanning={isScanning} />
        </section>

        {/* ── Scan Error ── */}
        {scanError && (
          <div className="max-w-2xl mx-auto my-6 px-4 animate-fade-up">
            <div className="rounded-2xl p-5 flex items-start gap-4"
              style={{ background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.25)' }}>
              <div className="shrink-0 h-9 w-9 rounded-xl flex items-center justify-center"
                style={{ background: 'rgba(239,68,68,0.15)' }}>
                <AlertTriangle className="h-5 w-5 text-rose-400" />
              </div>
              <div>
                <h4 className="font-bold text-rose-300 text-sm mb-1">Scan Failed</h4>
                <p className="text-rose-400/80 text-xs leading-relaxed">{scanError}</p>
              </div>
            </div>
          </div>
        )}

        {/* ── Scan Progress ── */}
        {isScanning && <ScanProgress targetUrl={targetUrl} />}

        {/* ── Results ── */}
        {!isScanning && currentReport && <ReportView report={currentReport} />}

        {/* ── Feature cards (welcome state) ── */}
        {showHero && (
          <section className="max-w-6xl mx-auto mt-6 mb-16 px-4">
            <p className="text-center text-xs font-semibold text-slate-600 uppercase tracking-widest mb-6">
              Everything included — no account needed
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {FEATURE_CARDS.map(({ icon: Icon, title, desc, color, bg, border }, i) => (
                <div
                  key={title}
                  className="rounded-2xl p-5 transition-all duration-300 group cursor-default animate-fade-up"
                  style={{
                    background: bg,
                    border: `1px solid ${border}`,
                    animationDelay: `${i * 60}ms`,
                    animationFillMode: 'both',
                  }}
                  onMouseEnter={e => e.currentTarget.style.transform = 'translateY(-2px)'}
                  onMouseLeave={e => e.currentTarget.style.transform = 'translateY(0)'}
                >
                  <div className="h-9 w-9 rounded-xl flex items-center justify-center mb-3"
                    style={{ background: `${color}20` }}>
                    <Icon className="h-4.5 w-4.5" style={{ height: 18, width: 18, color }} />
                  </div>
                  <h3 className="text-sm font-bold text-white mb-1.5">{title}</h3>
                  <p className="text-xs text-slate-400 leading-relaxed">{desc}</p>
                </div>
              ))}
            </div>
          </section>
        )}
      </main>

      {/* Footer */}
      <footer className="py-6 text-center text-[11px] text-slate-600"
        style={{ borderTop: '1px solid rgba(255,255,255,0.05)' }}>
        AI Accessibility Auditor &nbsp;·&nbsp; Powered by Playwright, axe-core &amp; LLM Engine
      </footer>

      <ApiKeyModal
        isOpen={isApiKeyOpen}
        onClose={() => setIsApiKeyOpen(false)}
        onSaveApiKey={(k) => setApiKey(k)}
        currentApiKey={apiKey}
      />
      <HistoryDrawer
        isOpen={isHistoryOpen}
        onClose={() => setIsHistoryOpen(false)}
        onSelectReport={handleSelectHistory}
      />
    </div>
  );
}
